a.out : main.c ./decomp/lyrics_decompression.c ./print/print.c ./mplayerfile/start_mplayer.c ./pos/console.c
	gcc -g main.c ./decomp/lyrics_decompression.c ./print/print.c ./mplayerfile/start_mplayer.c ./pos/console.c -o a.out
